### PR TITLE
Reimplement script_fetch via direct HTTP requests

### PR DESCRIPTION
**Pull request by jakovsch**
## What?
Making NEO queries does not need a whole browser (and webdriver executable).
A simpler solution is to fetch the NEO confirmation page, find and parse its table and build a request payload.
The endpoint for those is https://cgi.minorplanetcenter.net/cgi-bin/confirmeph2.cgi

No external dependencies are required for doing this.

## Where?
This implementation does not depend on existing code, so it should be separate.
Rewriting the project as a package is also a good idea, so I've put it under `neo_autoscript`
(for example: `main.py` to `neo_autoscript/__main__.py`)

This module can for now be run with `python -m neo_autoscript.script_fetch`

### CODE REVIEW

**Comment by 9helix** [comment]
Your method stores data from CGI site to HTML file, but to process the text I only need the text from the site without tags to remove unnecessary data. I managed to do it using selenium which extracts only the text from the website. I haven't found a method on how to do it using only the built-in modules.
[This](https://github.com/9helix/NEO-Autoscript/files/7189711/text.data.txt) is how the output should look like for my current processing method I use.

**Comment by jakovsch** [comment]
Yes, the script up to that commit was roughly equivalent to `get_ephem.click()` from `main`.

Take a look at the current code, it should now be at parity with the original.

**Comment by 9helix** [comment]
@jakovsch I implemented your method of data gathering in my project. Thanks for your help!

**Comment by jakovsch** [comment]
No problem.

Also, you don't need to manually load shared data (from the pickle file) to use it, that's what `utils.PersistentData` is for. It gets instanced only once, the first time utils.py is imported. It will update its attributes with the ones stored in that file.
I probably should've documented that..

**Pull request closed without merging**
